name: 'sales_pipeline'
version: '1.0.0'
config-version: 2

profile: 'dbt_fab_spark'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  sales_pipeline:
    staging:
      +materialized: view
      +schema: stg
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      +schema: mrt
seeds:
  sales_pipeline:
    raw:
      +schema: raw
      +quote_columns: false
