name: 'sales_pipeline'
version: '1.0.0'
config-version: 2

profile: 'dbt_fab_spark'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

dispatch:
  - macro_namespace: elementary
    search_order:
      - sales_pipeline
      - elementary_fabricspark
      - elementary

models:
  +workspace_name: "vibedata-prd-sales-pipeline"
  sales_pipeline:
    staging:
      +materialized: view
      +schema: stg
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      +schema: mrt
  elementary:
    +schema: elementary
    +tags: ["elementary"]

seeds:
  sales_pipeline:
    raw:
      +schema: raw
      +quote_columns: false
